### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by MrWwei** [yaoyichen/CIKM-Cup-2017#8]
CIKM2017_testA slice_ind: 0193
Traceback (most recent call last):
  File "step1.3_temporal_match_test.py", line 45, in <module>
    img2,N_row,N_col = read_slice(input_file,slice_size,slice_id2,T_id2,H_id)
  File "../TOOLS/CIKM_TOOLS.py", line 40, in read_slice
    _,row,col,pos = size_file[size_file.slice_id ==slice_ind].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by qiu-a11** [comment]
I have the same problem, did you solve it? Is this due to python version compatibility issues?
